Changelog version

diff --git a/.github/workflows/create_release.yaml b/.github/workflows/create_release.yaml
--- a/.github/workflows/create_release.yaml
+++ b/.github/workflows/create_release.yaml
@@ -18,11 +18,14 @@ jobs:
       - name: Checkout source
         uses: actions/checkout@v3
 
-      - name: Check version in tpay.php
-        run: if [ $(grep -e "$this->version = '${{ github.event.inputs.version }}';" tpay.php -c) != 1 ]; then exit 1; fi
-
-      - name: Check Changelog
-        run: if [ $(grep ${{ github.event.inputs.version }} CHANGELOG.MD -c) != 1 ]; then exit 1; fi
+      - name: Check version
+        run: |
+          for FILE in tpay.php config.xml config_pl.xml CHANGELOG.MD; do
+            if [ $(grep ${{ github.event.inputs.version }} "$FILE" -c) != 1 ]; then
+              echo "Version ${{ github.event.inputs.version }} not found in $FILE"
+              exit 1
+            fi
+          done
 
       - uses: shivammathur/setup-php@v2
         with:
